### ISSUE TITLE
Multiple fixtures initialized instead of one.

### ISSUE THREAD

**Issue by sergey-bulavskiy** [JDCain/Xunit.Extensions.AssemblyFixture#11]
Hello! 

I've encountered a strange problem when there is two fixtures being initialized and used (each for project) instead of one assembly-level fixture. 

What i'm trying to do: 
1. Created fixture with `IAsyncLifetime` interface implemented in the separate infrastructure-library project which is referenced by other test projects.
2. Added `AssemblyInfo.cs` to second and third test projects with next content: 
```C#
using Xunit;
using Xunit.Extensions.AssemblyFixture;

[assembly: TestFramework(AssemblyFixtureFramework.TypeName, AssemblyFixtureFramework.AssemblyName)]
``` 
3. Each test class inherits from TestBase class (infrastructure logic) which inherits `IAssemblyFixture`

```C#
public abstract class TestBase_new : IAsyncLifetime, IAssemblyFixture<AssemblyRespawnFixture>
{
    ... 
}
```

Somehow this leads to creation of two different AssemblyRespawnFixture objects instead of one. 

Am i doing something wrong ?

(Running tests in Jetbrains Rider via built-in test runner)

**Comment by JDCain** [comment]
To be clear you have three projects? Two which run tests and a third which houses the fixture? 
Each of those test projects are their own separate assemblies as far as xUnit and the test runners are concerned, so it's going to spin up two copies. 

The `AssemblyFixture` can share across classes and collections in the same project but not across multiple projects.

**Comment by sergey-bulavskiy** [comment]
Yeah, i had an impression that CollectionFixture fits role of per-project fixture, and for some reason thought that AssemblyFixture would work as one per multiple projects, but i was wrong. Thank you, closing the issue!
