### ISSUE TITLE
AssemblyFixture not working in net48 target

### ISSUE THREAD

**Issue by pergardebrink** [JDCain/Xunit.Extensions.AssemblyFixture#2]
Hi, I have some projects that now needs to target netcoreapp3.1 and some that still target net48 and using a shared project with fixtures, so I tried to move from the xunit.assemblyfixtures to your project to support .NET Core.. 

However, it seems as your project only supports .NET Core and not full framework, which I found out after some debugging that seems to be because the xunit.extensibility.execution library depends on xunit.execution.dotnet.dll when included from a netstandard2.0 library, while the net452 depends on xunit.execution.desktop.dll (the one the runner is using when testing full framework versions)

Is it possible to just add another target for your project to include net452 so that it can be used from both full framework and .NET Core?

**Comment by pergardebrink** [comment]
I added a pull request now to add target for .NET Framework as well.

**Comment by JDCain** [comment]
Closing as merged code is released in 2.2.
